# Competição DSA de Machine Learning
## Edição Janeiro/2019

# Análise Exploratória

### Variaveis
- num_gestacoes: Número de vezes grávida
- glicose: Concentração plasmática de glicose em teste oral de tolerância à glicose
- pressao_sanguinea: Pressão arterial diastólica em mm Hg
- grossura_pele: Espessura da dobra da pele do tríceps em mm
- insulina: Insulina em mu U / ml
- bmi: Índice de massa corporal medido em peso em kg / (altura em m) ^ 2
- indice_historico: Índice de histórico de diabetes (Pedigree Function)
- idade: Idade em anos
- classe: Classe (0 - não desenvolveu a doença / 1 - desenvolveu a doença)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_csv('diabetes.csv', 
                   header = None, sep = ",",
                   names=['Pregnancy', 'Glucose', 'BloodPressure' ,'SkinfoldThickness', 'Insulin', 'BodyMassIndex', 'DiabetesPedigreeFunction', 'Age', 'Class'])

In [28]:
print("Número de observações: %s \nNúmero de variaveis: %s" % (df.shape[0], df.shape[1]))
print(df.info())
df.head()

Número de observações: 768
Número de variaveis: 9
<class 'pandas.core.frame.DataFrame'>
Int64Index: 768 entries, 1 to 768
Data columns (total 9 columns):
Pregnancy                   768 non-null int64
Glucose                     768 non-null int64
BloodPressure               768 non-null int64
SkinfoldThickness           768 non-null int64
Insulin                     768 non-null int64
BodyMassIndex               768 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null int64
Class                       768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 60.0 KB
None

,Pregnancy,Glucose,BloodPressure,SkinfoldThickness,Insulin,BodyMassIndex,DiabetesPedigreeFunction,Age,Class
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0
5,0,137,40,35,168,43.1,2.288,33,1

In [29]:
df.describe()

,Pregnancy,Glucose,BloodPressure,SkinfoldThickness,Insulin,BodyMassIndex,DiabetesPedigreeFunction,Age,Class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000